### ISSUE TITLE
How can we make sure that dependencies are automatically tracked

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.observability#468] opened 2022-10-04 20:03 UTC
**Is your feature request related to a problem? Please describe.**

When creating an API that uses Arcus.Observability for logging to Application Insights, dependencies to SQL Server are not automatically tracked.

However, when I would use the default ApplicationInsights integration that is provided by Microsoft, calls to SQL Server are automatically tracked in AppInsights:

![image](https://user-images.githubusercontent.com/3605786/193914671-c595db38-676e-440d-ae95-0ed8d667e5a6.png)

In the above screenshot, I've configured Arcus.Observability logging and I've also made sure that I've added MS Application Insights middleware by calling `builder.Services.AddApplicationInsightsTelemetry()`.

As you can see, the dependency to SQL Server is tracked and the request is tracked twice (once by Arcus, once by Microsoft).
However, If I remove the `AddApplicationInsightsTelemetry` method call, then the dependency to SQL server is no longer logged.

How come this is not logged anymore ?  My guess would be that the dependency is logged by the Microsoft.Data.SqlClient package, and not by the MSFT Application Insights middleware itself.  However, there must be something that happens inside that middleware that makes it possible.

**Describe the solution you'd like**
When using Arcus Observability for logging, dependencies to other systems should also be automatically tracked, just like it is done out-of-the-box.

**Comment by fgheysels** [comment] 2022-10-04 20:14
I've been looking into the code of the SqlClient library, but cannot find any calls to log requests there, so it must be done via the Application Insights middleware ?

**Comment by fgheysels** [comment] 2022-10-04 20:59
The ApplicationInsights sdk contains a `DependencyCollector` project that contains some interesting types.

If we look at the `AddApplicationInsights` extension method from Microsoft, we can see there's a call to a method which is called `AddCommonTelemetryModules` which in turn seems to set up dependency tracking:

![image](https://user-images.githubusercontent.com/3605786/193926424-55392045-61e3-4c8c-a6de-e5953312cb5f.png)

The `AddAndConfigureDependencyTracking` method sets up the `DependencyTrackingTelemetryModule`  which is defined in the DependencyCollector assembly.

I think we should investigate if we can leverage this functionality from our Arcus middleware as well.

**Comment by fgheysels** [comment] 2022-10-04 21:28
Just additional information:
To have best of both worlds (automatic dependency tracking & Arcus logging extension methods), I've setup Serilog as a logger with the Arcus ApplicationInsights sink, but I'm not using the Arcus request-tracking middleware; instead, I'm using the Microsoft middleware.

**Comment by stijnmoreels** [comment] 2022-10-05 04:33
That's an interesting idea. If we could have something that does this for us. Previously, Microsoft was using activities to do this. And each dependency was starting an activity which was tracked.
It is also worth noting that the dependencies that we allow tracking, are far more extensible and customizable, for ex: passing additional contextual values.

**Comment by stijnmoreels** [comment] 2022-10-05 05:08
A quick view showed that there's an observer looking for general diagnostic events, and if the events matches a given SQL name, then it is considered from the SQL client. Maybe we can define our own observer and use our own logging system.

**Comment by fgheysels** [comment] 2022-10-05 07:02
> That's an interesting idea. If we could have something that does this for us. Previously, Microsoft was using activities to do this. And each dependency was starting an activity which was tracked. It is also worth noting that the dependencies that we allow tracking, are far more extensible and customizable, for ex: passing additional contextual values.

That's true, but having this out of the box is really very valuable: you don't have to do it yourself, and you already have a ton of information out of the box.
In Asp.Net core, you can now also choose to disable the automatic dependency tracking, so that's something we could also do if people want to do it theirselves and have more control.

**Comment by stijnmoreels** [comment] 2022-10-05 07:55
Yeah, that would be nice, the problem is that we handle correlation differently. We use user-defined correlation accessors so that people are able to extend on the correlation and use the correlation outside Microsoft-specific dependencies. The problem is that all Microsoft dependencies are using Activities instead of dependency injection to handle correlation.
We could try to move towards that approach, but it will have to be with the new W3C transition too, plus, we would have to rework our entire correlation Serilog enricher, too. Will need a lot of analysis for that.

**Comment by fgheysels** [comment] 2022-12-13 12:45
I think this can be closed ?

**Comment by stijnmoreels** [comment] 2022-12-14 07:20
It should be okay now, indeed. This also includes Messaging, but that is not yet released, though.

**Comment by stijnmoreels** [comment] 2023-01-11 07:28
Ok, now we can close this! 😄

**Closed by stijnmoreels** 2023-01-11 07:28 UTC
